import 'package:hive_flutter/hive_flutter.dart';

import '../../data/models/draft_model.dart';
import '../../data/models/shortlist_item_model.dart';
import '../../data/models/user_model.dart';
import '../constants/app_keys.dart';
import 'logger_service.dart';

/// Owns Hive lifecycle: `initFlutter()`, adapter registration, and the
/// always-open `settings` box that [StorageService] reads from.
///
/// Feature-specific caches (drafts page, brand profile, …) open their own
/// boxes lazily inside their repository module — keeps app startup cheap and
/// keeps box ownership co-located with the code that uses it.
///
/// Adapter registrations land here as Phase 2 introduces Hive-backed models.
class DbService {
  final LoggerService _log;
  bool _initialized = false;

  DbService(this._log);

  Future<void> init() async {
    if (_initialized) return;

    await Hive.initFlutter();

    _registerAdapters();

    await Hive.openBox<dynamic>(AppKeys.hiveBoxes.settings);

    _initialized = true;
    _log.i('DbService ready');
  }

  /// Register every adapter generated by `hive_generator`. Order doesn't
  /// matter as long as each runs exactly once before the first box open.
  /// Add new adapters here as Hive-backed models land in later phases.
  void _registerAdapters() {
    Hive.registerAdapter(UserModelAdapter());
    Hive.registerAdapter(ShortlistItemModelAdapter());
    Hive.registerAdapter(ShortlistGenerationStatusAdapter());
    Hive.registerAdapter(DraftModelAdapter());
  }

  /// Open (or return) a typed box. Repositories call this rather than
  /// `Hive.openBox` directly so the box-name set stays grep-able.
  Future<Box<T>> openBox<T>(String name) async {
    if (Hive.isBoxOpen(name)) {
      return Hive.box<T>(name);
    }
    return Hive.openBox<T>(name);
  }

  Future<void> close() async {
    if (!_initialized) return;
    await Hive.close();
    _initialized = false;
  }
}
